### ISSUE TITLE
"exec format error"

### ISSUE THREAD

**Issue by chazragg** [carlosedp/minecraft-server-arm64#2]
when running 
`docker run -d -it -e EULA=TRUE -p 25565:25565 --name mc carlosedp/minecraft-server:arm64 `

the server refuses to start and the logs show exec user process causes exec format error" 

currently trying to run it on a raspberry pi 3 b

**Comment by carlosedp** [comment]
Your Pi is probably running a 32bit Linux and this image is ARM64 for 64bit Linux.

Check with `uname -m` if it's `aarch64`.

**Comment by chazragg** [comment]
ahh, my bad I just did some reading up on my pi and misunderstood, I think it can do 64 bit but the raspbian line of operating systems are all 32-bit. thanks for the help.

**Comment by carlosedp** [comment]
@chazragg Take a look into [DietPi](https://dietpi.com/) or [Armbian](https://www.armbian.com/), they both are 64bit Linux.
